# Contains environment variables that may need to be overwritten by extraEnvs.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "langsmith.fullname" . }}-config
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
data:
  {{- if .Values.config.oauth.enabled }}
  VITE_BACKEND_AUTH_TYPE: "oauth"
  AUTH_TYPE: "oauth"
  {{- else }}
  VITE_BACKEND_AUTH_TYPE: "none"
  AUTH_TYPE: "none"
  {{- end }}
  LANGCHAIN_ENV: "local_kubernetes"
  FF_CLICKHOUSE_ENABLED: "true"
  CLICKHOUSE_DB: "default"
  CLICKHOUSE_HOST: {{ include "langsmith.fullname" . }}-{{ .Values.clickhouse.name }}
  CLICKHOUSE_PORT: "8123"
  CLICKHOUSE_USER: "clickhouse_admin"
  CLICKHOUSE_PASSWORD: "password"
