# Contains environment variables that may need to be overwritten by extraEnvs.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "langsmith.fullname" . }}-config
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
data:
  {{- if .Values.config.oauth.enabled }}
  VITE_BACKEND_AUTH_TYPE: "oauth"
  AUTH_TYPE: "oauth"
  {{- else if and .Values.config.basicAuth.enabled (eq .Values.config.authType "mixed") }}
  AUTH_TYPE: "mixed"
  BASIC_AUTH_ENABLED: true
  {{- else }}
  VITE_BACKEND_AUTH_TYPE: "none"
  AUTH_TYPE: "none"
  {{- end }}
  LANGCHAIN_ENV: "local_kubernetes"
  INGESTION_QUEUE: "default"
  ADHOC_QUEUE: "default"
  RUN_RULES_QUEUE: "default"
  GO_ENDPOINT: "http://{{ include "langsmith.fullname" . }}-{{ .Values.platformBackend.name }}:{{ .Values.platformBackend.service.port }}"
