config:
  langsmithLicenseKey: "YOUR_LICENSE_KEY"
  apiKeySalt: "YOUR_API_KEY_SALT"

# Note, you likely should tweak the values to match your needs
backend:
  deployment:
    resources:
      requests:
        cpu: 500m
        memory: 1000Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50

hubBackend:
  deployment:
    resources:
      requests:
        cpu: 500m
        memory: 1000Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50

frontend:
  deployment:
    resources:
      requests:
        cpu: 500m
        memory: 1000Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50

playground:
  deployment:
    resources:
      requests:
        cpu: 500m
        memory: 1000Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50

queue:
  deployment:
    requests:
      cpu: "1000m"
      memory: "4Gi"
  autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 10
      targetCPUUtilizationPercentage: 50
