config:
  langsmithLicenseKey: "YOUR_LICENSE_KEY"
  apiKeySalt: "YOUR_API_KEY_SALT"
  authType: "mixed"
  basicAuth:
    enabled: true
    initialOrgAdminEmail: "youremail@corp.dev"
    initialOrgAdminPassword: "TestLangSmith123!"
    jwtSecret: "YOUR_JWT_SECRET"
