config:
  langsmithLicenseKey: "YOUR_LICENSE_KEY"
  apiKeySalt: "YOUR_API_KEY_SALT"
  openaiApiKey: "YOUR OPENAI API KEY"
  oauth:
    enabled: true
    oauthClientId: "YOUR_CLIENT_ID"
    oauthIssuerUrl: "YOUR_ISSUER_URL"

# Note, you likely should tweak the values to match your needs
backend:
  deployment:
    resources:
      requests:
        cpu: "500m"
        memory: "1000Mi"
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50

hubBackend:
  deployment:
    resources:
      requests:
        cpu: "500m"
        memory: "1000Mi"
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50

frontend:
  deployment:
    resources:
      requests:
        cpu: "500m"
        memory: "1000Mi"
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50

playground:
  deployment:
    resources:
      requests:
        cpu: "500m"
        memory: "1000Mi"
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50

queue:
  deployment:
    resources:
      requests:
        cpu: "1000m"
        memory: "4Gi"
  autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 10
      targetCPUUtilizationPercentage: 50

# We suggest using an external database for production use cases.
postgres:
  external:
    enabled: true
    connectionUrl: "default:foo@host:port/database?sslmode=require"
    # existingSecretName: "postgres-secret" Can also put the above into a secret if you want to avoid putting the connection string in the values file.

# We suggest using an external redis for production use cases.
redis:
  external:
    enabled: true
    connectionUrl: "redis://host:port"
    # existingSecretName: "redis-secret" Can also put the above into a secret if you want to avoid putting the connection string in the values file.

clickhouse:
  statefulSet:
    resources:
      requests:
        cpu: "2000m"
        memory: "8Gi"
    persistence:
      size: "50Gi"
