apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "langsmith.fullname" . }}-{{ .Values.backend.name }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
data:
  nginx-unit-config.json: |
    {
      "listeners": {
          "*:{{ .Values.backend.containerPort }}": {
              "pass": "routes/main"
          }
      },
      "routes": {
          "main": [
              {
                  "match": {
                      "method": "OPTIONS"
                  },
                  "action": {
                      "return": 200,
                      "response_headers": {
                          "Access-Control-Allow-Credentials": "true",
                          "Access-Control-Allow-Origin": "$header_origin",
                          "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, PATCH, OPTIONS, HEAD",
                          "Access-Control-Allow-Headers": "$header_access_control_request_headers",
                          "Access-Control-Max-Age": "86400"
                      }
                  }
              },
              {
                  "action": {
                      "pass": "applications/fastapi",
                      "response_headers": {
                          "Cache-Control": "no-cache",
                          "Access-Control-Allow-Credentials": "true",
                          "Access-Control-Allow-Origin": "$header_origin"
                      }
                  }
              }
          ]
      },
      "applications": {
          "fastapi": {
              "type": "python 3.11",
              "path": "/code/smith-backend",
              "module": "app.main",
              "callable": "app"
          }
      },
      "settings": {
          "http": {
              "max_body_size": 26214400
          }
      }
    }
