{{- if not .Values.config.basicAuth.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langsmith.basicAuthSecretName" .}}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
data:
  initial_org_admin_password: {{ .Values.config.basicAuth.initialOrgAdminPassword | b64enc }}
  jwt_secret: {{ .Values.config.basicAuth.jwtSecret | b64enc }}
{{- end }}
