{{- if not .Values.config.basicAuth.existingSecretName }}

{{- $secretName := include "langsmith.basicAuthSecretName" . }}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}

{{- $jwtSecretFromValues := .Values.config.basicAuth.jwtSecret | default "" }}
{{- $jwtSecretFromSecret := (get $secretData "jwt_secret") | default "" }}
{{- $jwtSecret := ternary (b64enc $jwtSecretFromValues) $jwtSecretFromSecret (empty $jwtSecretFromValues) }}

{{- $initialOrgAdminPasswordFromValues := .Values.config.basicAuth.initialOrgAdminPassword | default "" }}
{{- $initialOrgAdminPasswordFromSecret := (get $secretData "initial_org_admin_password") | default "" }}
{{- $initialOrgAdminPassword := ternary (b64enc $initialOrgAdminPasswordFromValues) $initialOrgAdminPasswordFromSecret (empty $initialOrgAdminPasswordFromValues) }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
data:
  jwt_secret: {{ $jwtSecret }}
  initial_org_admin_password: {{ $initialOrgAdminPassword }}
{{- end }}
