{{- if .Values.config.fullTextSearch.enabled -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "langsmith.fullname" . }}-{{ .Values.quickwit.indexer.name }}
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
    {{- with.Values.quickwit.indexer.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
    {{- with .Values.quickwit.indexer.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if hasKey .Values.quickwit.indexer "replicaCount" }}
  replicas: {{ .Values.quickwit.indexer.replicaCount }}
  {{- end }}
  serviceName: {{ include "langsmith.fullname" . }}-{{ .Values.quickwit.name }}-headless
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      {{- include "quickwit.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "langsmith.fullname" . }}-{{ .Values.quickwit.indexer.name }}
  updateStrategy:
    {{- toYaml .Values.quickwit.indexer.updateStrategy | nindent 4 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config-map.yaml") . | sha256sum }}
      {{- with .Values.quickwit.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.quickwit.indexer.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "quickwit.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ include "langsmith.fullname" . }}-{{ .Values.quickwit.indexer.name }}
    spec:
      {{- with .Values.images.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "quickwit.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.quickwit.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.quickwit.name }}
          securityContext:
            {{- toYaml .Values.quickwit.securityContext | nindent 12 }}
          image: "{{ .Values.images.quickwitImage.repository }}:{{ .Values.images.quickwitImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.quickwitImage.pullPolicy }}
          args: ["run", "--service", "indexer"]
          env:
            {{- include "quickwit.environment" . | nindent 12 }}
            {{- range $key, $value := .Values.quickwit.indexer.extraEnv }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
          {{- if or (.Values.quickwit.environmentFrom) (.Values.quickwit.indexer.extraEnvFrom) }}
          envFrom:
          {{- with .Values.quickwit.environmentFrom }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.quickwit.indexer.extraEnvFrom }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          ports:
            {{- toYaml .Values.quickwit.ports | nindent 12 }}
          {{- toYaml .Values.quickwit.probes | nindent 10 }}
          volumeMounts:
            - name: config
              mountPath: /quickwit/node.yaml
              subPath: node.yaml
            - name: data
              mountPath: /quickwit/qwdata
            {{- with .Values.quickwit.indexer.extraVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.quickwit.indexer.resources | nindent 12 }}
      terminationGracePeriodSeconds: {{ .Values.quickwit.indexer.terminationGracePeriodSeconds }}
      volumes:
        - name: config
          configMap:
            name: {{ include "quickwit.configMapName" . }}
            items:
              - key: node.yaml
                path: node.yaml
        {{- if ne .Values.quickwit.indexer.persistentVolume.enabled true }}
        - name: data
          emptyDir: {}
        {{- end }}
        {{- with .Values.quickwit.indexer.extraVolumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.quickwit.indexer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with merge .Values.quickwit.affinity .Values.quickwit.indexer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.quickwit.indexer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.quickwit.indexer.persistentVolume.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "{{ .Values.quickwit.indexer.persistentVolume.storage }}"
      {{- if .Values.quickwit.indexer.persistentVolume.storageClass }}
        storageClassName: "{{ .Values.quickwit.indexer.persistentVolume.storageClass }}"
      {{- end }}
  {{- end }}
{{- end }}
