{{- if .Values.config.fullTextSearch.indexing.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "langsmith.fullname" . }}-{{ .Values.quickwit.metastore.name }}
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
    {{- with .Values.quickwit.metastore.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
    {{- with .Values.quickwit.metastore.deployment.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.quickwit.metastore.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "quickwit.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "langsmith.fullname" . }}-{{ .Values.quickwit.metastore.name }}
  strategy: {{- toYaml .Values.quickwit.metastore.deployment.strategy | nindent 4 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config-map.yaml") . | sha256sum }}
      {{- with .Values.quickwit.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.quickwit.metastore.deployment.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "quickwit.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ include "langsmith.fullname" . }}-{{ .Values.quickwit.metastore.name }}
    spec:
      {{- with .Values.images.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "quickwit.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.quickwit.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.quickwit.name }}
          securityContext:
            {{- toYaml .Values.quickwit.securityContext | nindent 12 }}
          image: "{{ .Values.images.quickwitImage.repository }}:{{ .Values.images.quickwitImage.tag }}"
          imagePullPolicy: {{ .Values.images.quickwitImage.pullPolicy }}
          args: ["run", "--service", "metastore"]
          env:
            {{- include "quickwit.environment" . | nindent 12 }}
            {{- range $key, $value := .Values.quickwit.metastore.deployment.extraEnv }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
          {{- if or (.Values.quickwit.environmentFrom) (.Values.quickwit.metastore.deployment.extraEnvFrom) }}
          envFrom:
          {{- with .Values.quickwit.environmentFrom }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.quickwit.metastore.deployment.extraEnvFrom }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          ports:
            {{- toYaml .Values.quickwit.ports | nindent 12 }}
          {{- toYaml .Values.quickwit.probes | nindent 10 }}
          volumeMounts:
            - name: config
              mountPath: /quickwit/node.yaml
              subPath: node.yaml
            - name: data
              mountPath: /quickwit/qwdata
            {{- with .Values.quickwit.metastore.deployment.extraVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.quickwit.metastore.deployment.resources | nindent 14 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "quickwit.configMapName" . }}
            items:
              - key: node.yaml
                path: node.yaml
        - name: data
          emptyDir: {}
        {{- with .Values.quickwit.metastore.deployment.extraVolumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.quickwit.metastore.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with  merge .Values.quickwit.affinity .Values.quickwit.metastore.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.quickwit.metastore.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
