{{- if .Values.config.fullTextSearch.indexing.enabled -}}
{{- if .Values.quickwit.searcher.statefulSet.podDisruptionBudget -}}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "langsmith.fullname" . }}-{{ .Values.quickwit.searcher.name }}
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "quickwit.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "langsmith.fullname" . }}-{{ .Values.quickwit.searcher.name }}
  {{- toYaml .Values.quickwit.searcher.statefulSet.podDisruptionBudget | nindent 2 }}
{{- end -}}
{{- end -}}
