{{- if .Values.config.fullTextSearch.enabled -}}
{{- if .Values.quickwit.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "quickwit.serviceAccountName" . }}
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
  {{- with .Values.quickwit.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
