{{- if .Values.config.fullTextSearch.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "quickwit.fullname" . }}-searcher
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.quickwit.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.quickwit.searcher.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.quickwit.searcher.serviceType | default .Values.quickwit.service.type }}
  {{- if .Values.quickwit.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.quickwit.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.quickwit.service.ipFamilies }}
  ipFamilies: {{ .Values.quickwit.service.ipFamilies | toYaml | nindent 2 }}
  {{- end }}
  ports:
    - port: 7280
      targetPort: rest
      protocol: TCP
      name: rest
    - port: 7281
      targetPort: grpc
      name: grpc
  selector:
    {{- include "quickwit.searcher.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "quickwit.fullname" . }}-headless
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.quickwit.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  {{- if .Values.quickwit.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.quickwit.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.quickwit.service.ipFamilies }}
  ipFamilies: {{ .Values.quickwit.service.ipFamilies | toYaml | nindent 2 }}
  {{- end }}
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-http
      port: 7280
      protocol: TCP
    - name: tcp-grpc
      port: 7281
      protocol: TCP
  selector:
    {{- include "quickwit.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "quickwit.fullname" . }}-indexer
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.quickwit.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.quickwit.indexer.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.quickwit.indexer.serviceType | default .Values.quickwit.service.type }}
  {{- if .Values.quickwit.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.quickwit.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.quickwit.service.ipFamilies }}
  ipFamilies: {{ .Values.quickwit.service.ipFamilies | toYaml | nindent 2 }}
  {{- end }}
  ports:
    - port: 7280
      targetPort: rest
      protocol: TCP
      name: rest
    - port: 7281
      targetPort: grpc
      name: grpc
  selector:
    {{- include "quickwit.indexer.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "quickwit.fullname" . }}-metastore
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.quickwit.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.quickwit.metastore.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.quickwit.metastore.serviceType | default .Values.quickwit.service.type }}
  {{- if .Values.quickwit.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.quickwit.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.quickwit.service.ipFamilies }}
  ipFamilies: {{ .Values.quickwit.service.ipFamilies | toYaml | nindent 2 }}
  {{- end }}
  ports:
    - port: 7280
      targetPort: rest
      protocol: TCP
      name: rest
    - port: 7281
      targetPort: grpc
      name: grpc
  selector:
    {{- include "quickwit.metastore.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "quickwit.fullname" . }}-control-plane
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.quickwit.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.quickwit.controlPlane.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.quickwit.controlPlane.serviceType | default .Values.quickwit.service.type }}
  {{- if .Values.quickwit.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.quickwit.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.quickwit.service.ipFamilies }}
  ipFamilies: {{ .Values.quickwit.service.ipFamilies | toYaml | nindent 2 }}
  {{- end }}
  ports:
    - port: 7280
      targetPort: rest
      protocol: TCP
      name: rest
    - port: 7281
      targetPort: grpc
      name: grpc
  selector:
    {{- include "quickwit.controlPlane.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "quickwit.fullname" . }}-janitor
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.quickwit.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.quickwit.janitor.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.quickwit.janitor.serviceType | default .Values.quickwit.service.type }}
  {{- if .Values.quickwit.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.quickwit.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.quickwit.service.ipFamilies }}
  ipFamilies: {{ .Values.quickwit.service.ipFamilies | toYaml | nindent 2 }}
  {{- end }}
  ports:
    - port: 7280
      targetPort: rest
      protocol: TCP
      name: rest
    - port: 7281
      targetPort: grpc
      name: grpc
  selector:
    {{- include "quickwit.janitor.selectorLabels" . | nindent 4 }}
{{- end }}
