{{- if .Values.config.fullTextSearch.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "langsmith.fullname" . }}-{{ .Values.quickwit.searcher.name }}
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
    {{- with .Values.quickwit.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.quickwit.searcher.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.quickwit.searcher.serviceType | default .Values.quickwit.service.type }}
  {{- if .Values.quickwit.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.quickwit.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.quickwit.service.ipFamilies }}
  ipFamilies: {{ .Values.quickwit.service.ipFamilies | toYaml | nindent 2 }}
  {{- end }}
  ports:
    - port: 7280
      targetPort: rest
      protocol: TCP
      name: rest
    - port: 7281
      targetPort: grpc
      name: grpc
  selector:
    {{- include "quickwit.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "langsmith.fullname" . }}-{{ .Values.quickwit.searcher.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "langsmith.fullname" . }}-{{ .Values.quickwit.name }}-headless
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
    {{- with .Values.quickwit.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  {{- if .Values.quickwit.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.quickwit.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.quickwit.service.ipFamilies }}
  ipFamilies: {{ .Values.quickwit.service.ipFamilies | toYaml | nindent 2 }}
  {{- end }}
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    # Needed by istio with mTLS mode set to STRICT.
    # The port names must starts with "tcp-" or "udp-" to work...
    # See https://istio.io/latest/docs/ops/common-problems/network-issues/#503-error-while-accessing-headless-services
    - name: udp
      port: 7282
      protocol: UDP
    - name: tcp-http
      port: 7280
      protocol: TCP
    - name: tcp-grpc
      port: 7281
      protocol: TCP
  selector:
    {{- include "quickwit.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "langsmith.fullname" . }}-{{ .Values.quickwit.indexer.name }}
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.quickwit.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.quickwit.indexer.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.quickwit.indexer.serviceType | default .Values.quickwit.service.type }}
  {{- if .Values.quickwit.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.quickwit.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.quickwit.service.ipFamilies }}
  ipFamilies: {{ .Values.quickwit.service.ipFamilies | toYaml | nindent 2 }}
  {{- end }}
  ports:
    - port: 7280
      targetPort: rest
      protocol: TCP
      name: rest
    - port: 7281
      targetPort: grpc
      name: grpc
  selector:
    {{- include "quickwit.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "langsmith.fullname" . }}-{{ .Values.quickwit.indexer.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "langsmith.fullname" . }}-{{ .Values.quickwit.metastore.name }}
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.quickwit.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.quickwit.metastore.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.quickwit.metastore.serviceType | default .Values.quickwit.service.type }}
  {{- if .Values.quickwit.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.quickwit.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.quickwit.service.ipFamilies }}
  ipFamilies: {{ .Values.quickwit.service.ipFamilies | toYaml | nindent 2 }}
  {{- end }}
  ports:
    - port: 7280
      targetPort: rest
      protocol: TCP
      name: rest
    - port: 7281
      targetPort: grpc
      name: grpc
  selector:
    {{- include "quickwit.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "langsmith.fullname" . }}-{{ .Values.quickwit.metastore.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "langsmith.fullname" . }}-{{ .Values.quickwit.controlPlane.name }}
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.quickwit.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.quickwit.controlPlane.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.quickwit.controlPlane.serviceType | default .Values.quickwit.service.type }}
  {{- if .Values.quickwit.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.quickwit.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.quickwit.service.ipFamilies }}
  ipFamilies: {{ .Values.quickwit.service.ipFamilies | toYaml | nindent 2 }}
  {{- end }}
  ports:
    - port: 7280
      targetPort: rest
      protocol: TCP
      name: rest
    - port: 7281
      targetPort: grpc
      name: grpc
  selector:
    {{- include "quickwit.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "langsmith.fullname" . }}-{{ .Values.quickwit.controlPlane.name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "langsmith.fullname" . }}-{{ .Values.quickwit.janitor.name }}
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.quickwit.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.quickwit.janitor.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.quickwit.janitor.serviceType | default .Values.quickwit.service.type }}
  {{- if .Values.quickwit.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.quickwit.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.quickwit.service.ipFamilies }}
  ipFamilies: {{ .Values.quickwit.service.ipFamilies | toYaml | nindent 2 }}
  {{- end }}
  ports:
    - port: 7280
      targetPort: rest
      protocol: TCP
      name: rest
    - port: 7281
      targetPort: grpc
      name: grpc
  selector:
    {{- include "quickwit.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "langsmith.fullname" . }}-{{ .Values.quickwit.janitor.name }}
{{- end }}
