{{- if not .Values.redis.external.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openGPTs.redisSecretsName" .}}
  labels:
    {{- include "openGPTs.labels" . | nindent 4 }}
  annotations:
    {{- include "openGPTs.annotations" . | nindent 4 }}
data:
  {{- if .Values.redis.external.enabled }}
    redis_connection_url: {{ .Values.redis.external.connectionUrl | b64enc }}
  {{- else }}
    redis_connection_url: {{ printf "redis://%s-%s:%v" (include "openGPTs.fullname" .) .Values.redis.name .Values.redis.containerPort | b64enc }}
  {{- end}}
{{- end }}
