apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "langsmith.fullname" . }}-{{ .Values.clickhouse.name }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
data:
  users.xml: |
    <clickhouse>
        <users>
            <default>
                <access_management>1</access_management>
                <named_collection_control>1</named_collection_control>
                <show_named_collections>1</show_named_collections>
                <show_named_collections_secrets>1</show_named_collections_secrets>
            </default>
        </users>
    </clickhouse>
