{{- if not .Values.clickhouse.external.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langsmith.clickhouseSecretsName" .}}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
data:
  {{- if .Values.clickhouse.external.enabled }}
  clickhouse_user: {{ .Values.clickhouse.external.user | b64enc }}
  clickhouse_password: {{ .Values.clickhouse.external.password | b64enc }}
  clickhouse_host: {{ .Values.clickhouse.external.host | b64enc }}
  clickhouse_port: {{ .Values.clickhouse.external.port | b64enc }}
  clickhouse_native_port: {{ .Values.clickhouse.external.nativePort | b64enc }}
  clickhouse_db: {{ .Values.clickhouse.external.database | b64enc }}
  {{- else }}
  clickhouse_user: {{ "default" | b64enc }}
  clickhouse_password: {{ "password" | b64enc }}
  clickhouse_host: {{ printf "%s-%s" (include "langsmith.fullname" .) .Values.clickhouse.name | b64enc }}
  clickhouse_port: {{ "8123" | b64enc }}
  clickhouse_native_port: {{ "9000" | b64enc }}
  clickhouse_db: {{ "default" | b64enc }}
  {{- end}}
{{- end }}
