apiVersion: v2
name: langgraph-cloud
maintainers:
  - name: Ankush
    email: ankush@langchain.dev
description: Helm chart to deploy the open-gpts application and all services it depends on.
type: application
version: 0.1.0
appVersion: "0.1.0"
