{{- if .Values.hubBackend.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hubBackend.serviceAccountName" . }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
    {{- with.Values.hubBackend.serviceAccount.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
    {{- with.Values.hubBackend.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
