{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "openGPTs.fullname" . }}-ingress
  annotations:
    {{- include "openGPTs.annotations" . | nindent 4 }}
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.hostname }}
  labels:
    {{- include "openGPTs.labels" . | nindent 4 }}
    {{- with .Values.ingress.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "openGPTs.fullname" . }}-{{ .Values.backend.name }}
            port:
              number: {{ .Values.backend.service.port }}
{{- end }}
