{{- if not .Values.config.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openGPTs.secretsName" . }}
  labels:
    {{- include "openGPTs.labels" . | nindent 4 }}
  annotations:
    {{- include "openGPTs.annotations" . | nindent 4 }}
data:
  openai_api_key: {{ .Values.config.openaiApiKey | b64enc | quote }}
  tavily_api_key: {{ .Values.config.tavilyApiKey | b64enc | quote }}
  kay_api_key: {{ .Values.config.kayApiKey | b64enc | quote }}
  ydc_api_key: {{ .Values.config.ydcApiKey | b64enc | quote }}
  azure_openai_deployment_name: {{ .Values.config.azureOpenaiDeploymentName | b64enc | quote }}
  azure_openai_api_key: {{ .Values.config.azureOpenaiApiKey | b64enc | quote }}
  azure_openai_api_base: {{ .Values.config.azureOpenaiApiBase | b64enc | quote }}
  azure_openai_api_version: {{ .Values.config.azureOpenaiApiVersion | b64enc | quote }}
  robocorp_action_server_url: {{ .Values.config.robocorpActionServerUrl | b64enc | quote }}
  robocorp_action_server_key: {{ .Values.config.robocorpActionServerKey | b64enc | quote }}
  connery_runner_url: {{ .Values.config.conneryRunnerUrl | b64enc | quote }}
  connery_runner_api_key: {{ .Values.config.conneryRunnerApiKey | b64enc | quote }}
{{- end }}
