{{- if not .Values.config.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openGPTs.secretsName" . }}
  labels:
    {{- include "openGPTs.labels" . | nindent 4 }}
  annotations:
    {{- include "openGPTs.annotations" . | nindent 4 }}
data:
  openai_api_key: {{ .Values.config.openaiApiKey | b64enc | quote }}
  tavily_api_key: {{ .Values.config.tavilyApiKey | b64enc | quote }}
  kay_api_key: {{ .Values.config.kayApiKey | b64enc | quote }}
  ydc_api_key: {{ .Values.config.ydcApiKey | b64enc | quote }}
{{- end }}
